# Medium size ontologies from http://lov.okfn.org/dataset/lov/sparql

PREFIX vann:<http://purl.org/vocab/vann/>
PREFIX voaf:<http://purl.org/vocommons/voaf#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT DISTINCT ?prefix ?uri ?title ?size {
	GRAPH <http://lov.okfn.org/dataset/lov>{
		?uri a voaf:Vocabulary .
        ?uri dct:title ?title .
		?uri vann:preferredNamespacePrefix ?prefix.
        ?uri dcat:distribution [
          voaf:classNumber ?classes ;
          voaf:propertyNumber ?properties
        ]
        BIND ((?classes+?properties) AS ?size)      
	}
  FILTER(?size <= 40 && ?size >= 20) .
} ORDER BY ?vocabPrefix
